// <auto-generated />
namespace GarageApp_MVC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class recpt : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(recpt));
        
        string IMigrationMetadata.Id
        {
            get { return "201712202015018_recpt"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
